### ISSUE TITLE
Factlist: Headline example on hover, should not have HTML.

### ISSUE THREAD

**Issue by livlab** [nprapps/portland2#15]
![image](https://cloud.githubusercontent.com/assets/1936365/8861220/e3c2cf16-313d-11e5-8910-275b86105ba6.png)

otherwise it shows the html on hover.

**Comment by alykat** [comment]
Hmm, works in the live site:

![image](https://cloud.githubusercontent.com/assets/491318/8863395/44d5ca6a-3166-11e5-9a9f-ed29fe5e1f32.png)
