### ISSUE TITLE
Waterbug: Getting 'Not a valid image URL' with any URL

### ISSUE THREAD

**Issue by livlab** [nprapps/portland2#29]
Tried a few valid URLs with images and I'm getting the error every time.

**Comment by TylerFisher** [comment]
This is only a bug with the Flask app.

**Comment by TylerFisher** [comment]
lol just kidding

**Comment by TylerFisher** [comment]
I honestly don't know how this ever worked. NPR images don't allow access, cross-origin, etc.

**Comment by TylerFisher** [comment]
Yeah, there's no way around the fact that most images do not have cross-origin headers on them. I think we just need to remove the remote URL loading feature from Waterbug.

**Comment by TylerFisher** [comment]
Closing in favor of #74
