### ISSUE TITLE
Name this thing

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/portland2#3]

**Comment by livlab** [comment]
- extrovert
- imaginator
- polaroid
- newstrovert
- darkroom
- newsmaginator
- mediator
- maripol
- mediapublic
- aidem
- mediamaker
- meditor
- mediatin' 
- image maker
- _png maker_ (because that's what it does)
- pngmkr
- pingmaker
- ping (because it sounds good with pym)

**Comment by livlab** [comment]
- DeBeliustator

**Comment by livlab** [comment]
- QuGaWa
- Danny

**Comment by livlab** [comment]
- PNGolin

**Comment by alykat** [comment]
- Social Butterfly
- DeBelibot
- Highlighter
- Amplifier
- Booster
- Soapbox
- Loudspeaker
- Prattlebot
- Informer
- Informant
- Ephemerator
- Ephemeron
- Efemera (esperanto!)
- Handbill

**Comment by TylerFisher** [comment]
Lunchbox!
