### ISSUE TITLE
Sign the app demos

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/portland2#39]

**Comment by livlab** [comment]
Windows signing
https://msdn.microsoft.com/en-us/library/windows/desktop/aa388151(v=vs.85).aspx

OSX signing
http://successfulsoftware.net/2012/08/30/how-to-sign-your-mac-os-x-app-for-gatekeeper/

**Comment by livlab** [comment]
Also, regarding Mac App Store http://www.saschawise.com/blog/2015/08/12/electron-for-the-mac-app-store.html

**Comment by TylerFisher** [comment]
Dropping support for electron.
