### ISSUE TITLE
PNG not appearing in exported images

### ISSUE THREAD

**Issue by matthewjonesaus** [nprapps/portland2#45]
In Quotable and Factlist, PNG logos appear in Preview, but do not appear in the exported image.

Preview: 
<img width="1167" alt="screen shot 2015-07-29 at 6 07 51 pm" src="https://cloud.githubusercontent.com/assets/4384846/8952745/2c35064a-361d-11e5-964b-6d243cc1c3d0.png">

Exported image:

![quote-steve-holt](https://cloud.githubusercontent.com/assets/4384846/8952759/3fcff91c-361d-11e5-8018-eeb054cc2992.png)

**Comment by TylerFisher** [comment]
Hmm... I can't replicate this. We use pngs for our NPR config and it works just fine:

![quote-ive-made-a-huge-mistake](https://cloud.githubusercontent.com/assets/1077075/8959608/c59239be-35d9-11e5-8a4f-f3fc7282b25c.png)

Can you put the png you're trying to use here so I can test with that?

**Comment by matthewjonesaus** [comment]
Sure, PNG is attached. Oddly, it only seems to happen on Windows - on Mac the logo appears when exported. Here's a link to the Windows installer we're using: https://www.dropbox.com/s/vtazu4aidsmyoc5/Lunchbox%20Setup.exe?dl=0
![skynewslogo](https://cloud.githubusercontent.com/assets/4384846/8973328/16f3bf12-36a7-11e5-8919-0fe1aa2ad62b.png)

Thanks!

**Comment by TylerFisher** [comment]
Hm, I ran this in a Windows 7 VM and was able to export properly. What version of Windows are you running? 
![quote-id-been-drinking](https://cloud.githubusercontent.com/assets/1077075/8985260/30eba130-368b-11e5-8a0b-55ca4f6cbdde.png)

Edit: Ran this in Windows 8.1 as well, same results.

**Comment by matthewjonesaus** [comment]
Bizarre - just installed Lunchbox on a fresh Win7 VM, and it works fine. I had previously tried it on three different Win7 PCs and the logo didn't appear in exported images on any of them.

Seems like it's a bit of an edge case, so probably not worth further investigation - but happy to help if you'd like to. Thanks for your help!

**Comment by TylerFisher** [comment]
Yeah, just can't replicate this. Closing until I see it again.
