### ISSUE TITLE
Version error on Windows machines

### ISSUE THREAD

**Issue by mtdukes** [nprapps/portland2#47]
Running the exe installer on my Windows machine gives me the following error:

> "The version of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher."

Running Windows 7 Professional, Service Pack 1, 64-bit operating system. Tried changing the `electron-packager` arch parameter in my [package.json](https://github.com/mtdukes/lunchbox/blob/master/package.json) to x64, but got the same error.

**Comment by TylerFisher** [comment]
Interesting. There's a good amount of testing I still have to do on various Windows machines. I'll play around with this.

**Comment by TylerFisher** [comment]
Dropping support for electron because IT policies in newsrooms and Windows apps aren't really working.
