### ISSUE TITLE
Quotable: Show Attribution default style bug

### ISSUE THREAD

**Issue by livlab** [nprapps/portland2#49]
The Show Attribution style is the same for all themes and doesn't work well with themes 3 and 4.

![image](https://cloud.githubusercontent.com/assets/1936365/8963144/8f1e20f6-35ec-11e5-9aa4-5c633718ee6f.png)

![image](https://cloud.githubusercontent.com/assets/1936365/8963172/bf9a02ea-35ec-11e5-8a92-07c442f5560a.png)

**Comment by TylerFisher** [comment]
Yeah, this should be configurable.
