### ISSUE TITLE
Variables.less - credit-color not rendering

### ISSUE THREAD

**Issue by livlab** [nprapps/portland2#51]
@credit-color is not rendering in the app, it's inheriting @text-color: setting. 

I tried to customize the app and modified @credit-color to a distinctive color and it had no effect in the app. Inspector shows it displaying the color in text-color instead.

Could not figure out where the change needs to occur.

**Comment by TylerFisher** [comment]
@credit-color is for the attribution, not the source, which is working for me.

**Comment by livlab** [comment]
Yes, I meant that.
I just started this again with a fresh clone and it worked. I don't know what was up. ¯_(ツ)_/¯
