### ISSUE TITLE
'save image' button dead on firefox?

### ISSUE THREAD

**Issue by dansinker** [nprapps/portland2#54]
in Quotable, when I hit "save image" either one of two things happens:
1) I get a dialogue telling me my quote doesn't fit and to reduce the font size
2) nothing

in safari (launched to check that I'm not nuts), #1 is still true (and works as expected), #2 opens a new window with the image.

**Comment by TylerFisher** [comment]
Ah yikes, not sure when that bug came back. Electron runs Chromium, so I haven't been testing Firefox as rigorously as I should, but we've solved this issue before.

**Comment by TylerFisher** [comment]
Oh ugh, SVG + Firefox + html2canvas don't play together. We use PNG assets on quotable/factlist for this reason. I should note that in the docs.

**Comment by TylerFisher** [comment]
RE: the Safari issue, that's just what Safari does with data URIs, unfortunately. You can still save from that new tab.

**Comment by dansinker** [comment]
Oh right, yes, I was pinging safari as the expected behavior.

**Comment by TylerFisher** [comment]
Closing in favor of #64
