### ISSUE TITLE
is there a way to make quote attribute *not* required?

### ISSUE THREAD

**Issue by dansinker** [nprapps/portland2#60]
I can see scenarios where I just want some text listed and don't need to attribute it. can I turn off the requirement for this and if I don't have it it'll just be blank?

**Comment by TylerFisher** [comment]
Hey Dan, check out `www/js/quotable.js` from the branch "quotable-no-source" [here](https://github.com/nprapps/lunchbox/blob/quotable-no-source/www/js/quotable.js). I don't think this is something we want to enable by default, but it's not too hard to monkey patch some of the code to make it work this way.

**Comment by TylerFisher** [comment]
there's a branch, but this is not desirable for us
