### ISSUE TITLE
Logos do not export in Quotable/Factlist on Windows machines

### ISSUE THREAD

**Issue by yelvington** [nprapps/portland2#66]
We did a quick test version and (after learning a whole lot about the toolchain) managed to build a Windows installer as well as a .dmg for OSX. 

When we create a quote, the Windows version is omitting the logo (which in our case is a .png file, not svg) from the downloadable image.

**Comment by TylerFisher** [comment]
This must be an issue with actual Windows machines only. It doesn't happen in any emulator I've ever used. I'll have to find a Windows machine I can actually use and install this on. Thanks for reporting.

**Comment by bchartoff** [comment]
+1 same issue in quotable. Logo renders with waterbug. We're using svg logos. Don't have any error log (not sure if there is one with electron exe?) Unclear how to debug, in large part bc windows ¯_(ツ)_/¯ and I don't want to take over my coworkers comp. If you have a concrete way to get a log etc. @TylerFisher I'm happy to hop on the windows machine for a sec...

**Comment by TylerFisher** [comment]
Okay. Thanks for reporting. Hoping I can get to this later in the week or early next week.

**Comment by bchartoff** [comment]
Not positive this is the right issue but https://github.com/maxogden/electron-packager/issues/53 could be a culprit. One thing to note, I built the exe on the Mac, then sent the exe to a windows user (and problems happened). @TylerFisher did you build and run on the same windows VM? If you did, rcedit.exe could have been installed and bundled with the .exe. I don't have rcedit.exe at:
 `node_modules/electron-packager/node_modules/.bin/rcedit.exe` Do you? Trying to get permissions to run build scripts on a PC but hitting some IT roadblocks...

**Comment by cb0wman** [comment]
I have a running build environment on a Windows 7 PC, and experience the same issue with Quoteable and Factlist described in this issue report.  I'm a newb for this build toolchain, but may be able to assist if given direction.

Update:
I ran Lunchbox from the build path (electron\Lunchbox-win32-ia32) and it works fine.  I wonder if there are 'special' permission issues being encountered when the installer places the files in the protected OS folder "Program Files (x86)"...

Update 2:
Added a directory destination Page to the NSIS install script (Lunchbox/node_modules/electron-builder/templates/installer.nsi.tpl - ln. 22 + !insertmacro MUI_PAGE_DIRECTORY)

Installed LunchBox to a directory outside of /Program Files and works like it should.  Permissions issue...  Tried running Lunchbox form default install location as Administrator, resulted in same no logo bug.

**Comment by TylerFisher** [comment]
Huuuuh. That's really interesting. Thank you for checking this out! I apologize for not having much time for Lunchbox recently, but this gives me a discrete thing to look into.

**Comment by NewsThisSecond** [comment]
Hopefully this gets fixed soon.

**Comment by TylerFisher** [comment]
Dropping support for Electron. This isn't going to work properly + IT policies at most news orgs make circulating a desktop app impossible.
