### ISSUE TITLE
App build fails on missing .dmg or .exe files

### ISSUE THREAD

**Issue by yelvington** [nprapps/portland2#67]
The app build process includes a step that removes the existing .dmg and .exe installer files from the working directory before proceeding. 

If the process fails after that point, the directory may be left with no .dmg or .exe file. Subsequent build attempts will choke and die when the "rm Lunchbox.dmg" or "rm 'Lunchbox Setup.exe'" try to remove a file that isn't there. 

It's easy to fix ("touch filename" before rm would do the trick).

**Comment by TylerFisher** [comment]
Decided to use the -f flag on the rm, but thanks for catching this.
