### ISSUE TITLE
Problem downloading some crops of some images in Chrome, or something

### ISSUE THREAD

**Issue by brianboyer** [nprapps/portland2#68]
From Ariel:

Here’s a couple examples. No problems making the 16x9 crop, but won’t save using the original crop. Chrome Version 45.0.2454.93 (screenshots attached). Worked fine in Firefox. Just an out-of-date browser?
![screen shot 2015-11-03 at 3 39 07 pm](https://cloud.githubusercontent.com/assets/68644/11072869/eef9c8fc-87b5-11e5-94ea-d25b0f081a29.png)
![screen shot 2015-11-03 at 3 40 38 pm](https://cloud.githubusercontent.com/assets/68644/11072872/f0bcae20-87b5-11e5-8ffc-ce523e7acd48.png)
![eu-hot-spot-01-jhilton](https://cloud.githubusercontent.com/assets/68644/11072875/f30ee68e-87b5-11e5-8a30-a6e022eb125b.jpg)
![rubber tappers 01](https://cloud.githubusercontent.com/assets/68644/11072877/f5e8cd8e-87b5-11e5-8551-c4c858ca2eff.jpg)

**Comment by TylerFisher** [comment]
Seems like this is no longer an issue. Can't replicate it.
