### ISSUE TITLE
Document installation and usage

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/portland2#7]

**Comment by livlab** [comment]
Include how to format your assets (transparent logo backgrounds, etc)

**Comment by livlab** [comment]
Add how to customize the app theme itself to match your org

**Comment by livlab** [comment]
note that logo sizing should be square or the other ratio we offer options for; that adjusting one's brand mark to work with the content will save time in customizing things in the long run

**Comment by livlab** [comment]
Documentation needs:
- For developer setting up, customizing and deploying this for their organization (README.md)
- For user of tool suite on how to use each of the tools (github pages)

**Comment by livlab** [comment]
Topics:
- What is this? (description of what the tool does and who it's for)
  - point to user guide for app usage (end-user focused on github pages)
- Assumptions (how it's going to be used, presumed expertise)
- What's in here? (how the repo is organized, what each folder contains)
- Quick Start (Bootstrap the project)
- Configuration
  - define global variables
  - where to place assets 
  - how to format assets
  - further customizing the app (for more fine-point customizations, where to change things
  - theming
- Run the project (using Electron)

**Comment by TylerFisher** [comment]
Done.
