### ISSUE TITLE
Add text overlay on Waterbug

### ISSUE THREAD

**Issue by IADDIC** [nprapps/portland2#73]
I'm loving the app and have made some serious use of it!  Thanks you for sharing.  As I've used it I find myself desiring one more feature (it's always just one more isn't i?).

The feature is to add a textera box over the image.  kind of like using the quotable and overlaying it on waterbug. The features would be the textera box and the text scaling slider.  

The feature should either be selectable (via a button) or ignored if "empty"

Any thoughts?

Is this something someone can help me do, or do you know of a fork that already does this?

Thanks,  Rich

**Comment by TylerFisher** [comment]
We use Waterbug specifically for crediting and not for text over the image -- this is an explicit design decision. If this is something you need, check out Vox's [meme](https://github.com/voxmedia/meme), which gives you a whole lot of control over something like that.
