### ISSUE TITLE
Issue with "fi" ligature in HTML2Canvas

### ISSUE THREAD

**Issue by davisshaver** [nprapps/portland2#75]
One of our producers noted that `fi` combo would result in the `i` being dropped. After some experimentation I discovered that the one-liner `font-feature-settings: "liga" 0;` in the CSS for the Quotable `blockquote` element fixed the issue. For consideration, I'll put together a pull request too.

![quote-finally-weve-fixed-it](https://cloud.githubusercontent.com/assets/1636964/14111803/24ea50a6-f59a-11e5-914a-507132d0ac44.png)

**Comment by eads** [comment]
Whoa!

**Comment by ghing** [comment]
Same. 
![quote-police-who-are-not-fit__square](https://cloud.githubusercontent.com/assets/110420/16158254/14b7f7de-3482-11e6-8c43-f0500089cdc7.png)

**Comment by eads** [comment]
@TylerFisher @jjelosua can one of you take a look into this?

**Comment by TylerFisher** [comment]
I'll take a look at @davisshaver's PR.

**Comment by TylerFisher** [comment]
Hm. I wonder if Gotham just doesn't have that ligature? What fonts are y'all using @davisshaver @ghing?

**Comment by ghing** [comment]
@TylerFisher I think I was just using whatever font is the default.  I think the only thing I overwrote in the CSS was the background color and logo image.

**Comment by TylerFisher** [comment]
Cool, replicated and merged @davisshaver's PR. Works great.

**Comment by cscouto** [comment]
I solve this problem using a condition to check if the word has "fi" in the html2canvas.js
`textList = ((!options.letterRendering && /^(left|right|justify|auto)$/.test(textAlign) && noLetterSpacing(getCSS(el, "letterSpacing"))) || (textNode.nodeValue.indexOf("fi") !== -1) ) ?`
