### ISSUE TITLE
black logo doesnt work

### ISSUE THREAD

**Issue by brianboyer** [nprapps/portland2#78]
white NPR logo works fine. when i change it to black, it disappears.

was reported by msingh@npr.org, i replicated on my machine: FF, OSX

![screen shot 2016-04-25 at 4 53 38 pm](https://cloud.githubusercontent.com/assets/68644/14798566/47a693ee-0b06-11e6-9bd4-d476d79808f4.png)

**Comment by TylerFisher** [comment]
Fixed by updating Illustrator svgs: fab38823f933a390d923b0adcf6c2c44e68ed02c
